/*****************************************************************************

@header@
@date@
@copyright@
@license@

*****************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTStart.java */
package org.nfunk.jep;

/**
 * Start Node
 */
public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Parser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
