/*****************************************************************************

JEP - Java Expression Parser
    JEP is a Java package for parsing and evaluating mathematical 
	expressions. It currently supports user defined variables, 
	constant, and functions. A number of common mathematical 
	functions and constants are included.

Author: Nathan Funk
Copyright (C) 2000 Nathan Funk

    JEP is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    JEP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with JEP; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*****************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTVarNode.java */

package org.nfunk.jep;

import java.util.*;
/**
 * Variable Node
 */
public class ASTVarNode extends SimpleNode {
	
	private String varName;
	
	public ASTVarNode(int id) {
		super(id);
		varName = "";
	}
	
	public ASTVarNode(Parser p, int id) {
		super(p, id);
	}
	
	/**
	 * Accept the visitor.
	 */
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	/**
	 * Sets the name of the variable.
	 */
	public void setName(String varName_in)
	{
		varName = varName_in;
	}
	
	/**
	 * Returns the name of the variable.
	 */
	public String getName()
	{
		return varName;
	}

	/**
	* Creates a string containing the variable's name and value
	*/
	public String toString()
	{
		String temp = "Variable: \"" + getName() + "\"";
		
		return temp;
	}
}
