/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.nfunk.jep;

public interface ParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 5;
  int DECIMAL_LITERAL = 6;
  int FLOATING_POINT_LITERAL = 7;
  int EXPONENT = 8;
  int STRING_LITERAL = 9;
  int IDENTIFIER = 10;
  int LETTER = 11;
  int DIGIT = 12;
  int ASSIGN = 13;
  int SEMI = 14;
  int COMMA = 15;
  int GT = 16;
  int LT = 17;
  int EQ = 18;
  int LE = 19;
  int GE = 20;
  int NE = 21;
  int AND = 22;
  int OR = 23;
  int PLUS = 24;
  int MINUS = 25;
  int MUL = 26;
  int DOT = 27;
  int DIV = 28;
  int MOD = 29;
  int NOT = 30;
  int POWER = 31;
  int CROSS = 32;
  int LSQ = 33;
  int RSQ = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"^\"",
    "\"^^\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
